### ISSUE TITLE
Integrate Cancer Biomarker Database

### ISSUE THREAD

**Issue by elipapa** [opentargets/data_pipeline#229]
@ckongEbi commented on [Thu Dec 14 2017](https://github.com/opentargets/data_release/issues/49)

The idea is to integrate data from https://cancergenomeinterpreter.org/biomarkers into the target profile page.

Tasks (to be expanded) :
- [x] Start Specifications document
- [x] Formulate Why and How the data should be integrated into the OT platform
- [x] Fill in info on data accessibility: license, update frequency, access
- [x] Replicate entries that have more than one drug (~80 entries), cancer type (~80 entries) or reference (> 100 entries) listed.
- [x] Construct links for the ~400 database entries that cite a conference abstract or FDA/NCCN guidelines.
- [x] Map gene names
- [ ] Map drug names (have compound names, 'chemotherapy' appears a few times)
- [x] Map diseases/cancer types (143 entries list 'Any cancer type’ as disease, 90 different diseases)
- [x] Look at the data_pipeline, gene merging step `--gen` , the plugin system
- [ ] Enrich/Map the initial dataset with Ensembl ID (biomarker) , Chembl ID (drug), Disease ID (Tumor type)
- [ ] Check over data in Open Targets frontend
- [x] Format individual_mutation field from FGFR3:V555M to FGFR3 (V555M)

**Comment by ElaineMcA** [comment]
New ticket will be raised for future updates of cancer biomarker data.
